#!/usr/bin/env python3
"""Regenerate the bundled emoji catalog from the pinned Unicode 17.0 data."""

import hashlib
import json
from pathlib import Path
import re
import urllib.request


SOURCE = "https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt"
SHA256 = "1d8a944f88d7952f7ef7c5167fef3c67995bcae24543949710231b03a201acda"
OUTPUT = Path(__file__).resolve().parents[1] / "internal/web/static/emoji-data.js"


def main():
    with urllib.request.urlopen(SOURCE, timeout=30) as response:
        source = response.read()
    if hashlib.sha256(source).hexdigest() != SHA256:
        raise SystemExit("Unicode data checksum mismatch; catalog not changed")

    groups = []
    for line in source.decode("utf-8").splitlines():
        if line.startswith("# group: "):
            groups.append({"name": line.removeprefix("# group: "), "emojis": []})
        match = re.fullmatch(r"([0-9A-F ]+); fully-qualified\s+# \S+ E[0-9.]+ (.+)", line)
        if match:
            emoji = "".join(chr(int(code, 16)) for code in match[1].split())
            groups[-1]["emojis"].append([emoji, match[2]])
    groups = [group for group in groups if group["emojis"]]

    # Keep one entry per line for readable diffs when updating Unicode versions.
    output = [
        "// Generated by scripts/update-emoji-data.py; do not edit by hand.",
        f"// Source: {SOURCE}",
        f"// SHA256: {SHA256}",
        "// Unicode License V3: see emoji-data.LICENSE.txt.",
        "const OPENMESSAGE_EMOJI_DATA = [",
    ]
    for group in groups:
        output.append("  { name: " + json.dumps(group["name"]) + ", emojis: [")
        output.extend("    " + json.dumps(entry, ensure_ascii=False) + "," for entry in group["emojis"])
        output.append("  ] },")
    output.append("];")
    OUTPUT.write_text("\n".join(output) + "\n", encoding="utf-8")
    print(f"Generated {sum(len(group['emojis']) for group in groups)} emoji entries")


if __name__ == "__main__":
    main()
